[project]
name = "skywrangler-web-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyproj>=3.7.1",
]

[dependency-groups]
test = [
    "pytest>=8.3.5",
]
